resource_group_name = "MyResourceGroup"
location            = "East US"
vnet_name           = "MyVNet"
subnet_name         = "MySubnet"
subnet2_name        = "MySubnet2"
subnet2_prefix      = "10.0.2.0/24"
